name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select input to update: extraVars, inventory, deploymentManifest'
        required: true
        default: 'extraVars'
        options:
          extraVars: 'Update extraVars'
          inventory: 'Update inventory'
          deploymentManifest: 'Update deploymentManifest'
  push:
    paths:
      - 'prod/*'
      - 'non-prod/*'

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          path: job_repo

      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'new_branch'

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: new_branch
          path: job_repo

      - name: PWD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./job_repo
          wbranch="`git branch`"
          printf "Current branch is ->"
          printf $wbranch

      - name: Create prod/ directories if not exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p job_repo/test; touch job_repo/test/.gitkeep; cat "hello" > job_repo/test/foo.txt #/extraVars
          # mkdir -p job_repo/prod/inventory; touch .gitkeep
          # mkdir -p job_repo/prod/deploymentManifest; touch .gitkeep

      - name: path
        run: |
          pwd

      - name: Validate Input
        id: validate_input
        run: |
          choice="${{ github.event.inputs.choice }}"
          if [[ $choice != "extraVars" && $choice != "inventory" && $choice != "deploymentManifest" ]]; then
            echo "Invalid choice. Please choose one of: extraVars, inventory, deploymentManifest"
            exit 1
          fi
          echo "::set-output name=CHOICE::$choice"

      - name: Run Script
        run: |
          choice="extraVars"
          case $choice in
            "extraVars")
              echo "Contents of non-prod/extraVars/ directory:"
              ls -l ./non-prod/extraVars/
              if [ -d "./non-prod/extraVars/" ]; then
                cp ./non-prod/extraVars/*.json ./prod/extraVars/ || (echo "Failed to copy JSON files." && exit 1)
                echo "Inputs updated for $choice"
              else
                echo "Directory ./non-prod/extraVars/ does not exist."
                exit 1
              fi
              ;;
            "inventory")
              # Similarly handle other cases
              ;;
            "deploymentManifest")
              # Similarly handle other cases
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac
        shell: bash


      - name: Git Add
        run: git add .

      - name: Git Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Automated update of ${{ github.event.inputs.choice }} dropdown inputs"

      - name: Git Push
        run: git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update ${{ github.event.inputs.choice }} dropdown inputs"
          branch: update-${{ github.event.inputs.choice }}-inputs
          commit-message: "Automated update of ${{ github.event.inputs.choice }} dropdown inputs"
          body: |
            Automated update of ${{ github.event.inputs.choice }} dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}
